2021-07-05 00:25:46,506 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9100) is connected !!!!
2021-07-05 00:25:46,508 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9100)
2021-07-05 00:25:46,512 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xe1\nrG\x0fy\xd7iKl' RpcHandler Destroy!
2021-07-05 00:25:46,514 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-05 00:25:46,516 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1e10a72470f79d7694b6d mem_id=1640058885120
2021-07-05 00:25:46,517 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1e10a72470f79d7694b6d 
2021-07-05 00:25:46,521 - INFO - TcpProtocol - [ConnMgr.py:53]: TCP ROLE_TYPE_ACTIVE peer_addr=('127.0.0.1', 9201) is connected !!!!
2021-07-05 00:25:46,548 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:46,566 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:49,546 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:49,558 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:52,553 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:52,564 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:55,574 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:55,584 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:58,576 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:25:58,589 - DEBUG - TcpConn - [ConnBase.py:233]: send_data_and_count: peer_addr=('127.0.0.1', 9201)
2021-07-05 00:26:00,006 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 9100), close_reason='[WinError 64] The specified network name is no longer available'
