2021-07-04 21:13:03,490 - INFO - TcpProtocol - [ConnMgr.py:52]: ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:22:44,591 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:22:44,597 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd2D\x08\xe0\xc3\x818\x82.\xbd' RpcHandler Destroy!
2021-07-04 23:22:44,599 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:22:44,601 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d24408e0c38138822ebe mem_id=2607114749744
2021-07-04 23:22:44,602 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d24408e0c38138822ebe 
2021-07-04 23:22:44,606 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:24:18,949 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9100) is connected !!!!
2021-07-04 23:24:18,954 - WARNING - RpcHandler - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\RpcHandler.py:83"]: self.rpc_handler_id=b'`\xe1\xd2\xa2z\x08\xe7\x07\xb7\x1a\xdaZ' RpcHandler Destroy!
2021-07-04 23:24:18,956 - DEBUG - __main__ - [TcpClient2.py:84]: lobby server info: ('gate_0', '127.0.0.1', 9201)
2021-07-04 23:24:18,958 - INFO - ServerEntity.Avatar - [ServerEntity.py:25]: __init__ create entity Avatar with id 60e1d2a27a08e707b71ada5b mem_id=1810372099856
2021-07-04 23:24:18,959 - INFO - server.EntityManager - [EntityManager.py:139]: addentity  entity id  60e1d2a27a08e707b71ada5b 
2021-07-04 23:24:18,964 - INFO - TcpProtocol - [ConnMgr.py:52]: TCP ('127.0.0.1', 9201) is connected !!!!
2021-07-04 23:35:01,080 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 9100), close_reason='[WinError 64] The specified network name is no longer available'
2021-07-04 23:35:11,608 - WARNING - TcpConn - ["C:\Users\b\Documents\github\realtime-server\pycharm2020.1.3\script\ConnBase.py:192"]: peer addr: ('127.0.0.1', 9201), close_reason='[WinError 64] The specified network name is no longer available'
